### ISSUE TITLE
Mention extension documentation is missing

### ISSUE THREAD

**Issue by abdullah-saqer** [ueberdosis/tiptap-docs#31]
Hello
Mention extension documentation is missing doesn't contain how to use it.
Link https://tiptap.dev/docs/api/extensions.html#mention

**Comment by hanspagel** [comment]
Thanks! We’ve never really written much documentation for tiptap 1, we didn’t expect that many people using it. That said, we’re in the process of writing extensive documentation for version 2. 🎉

Follow the process here: https://github.com/ueberdosis/tiptap/issues/547
