### ISSUE TITLE
Custom LLM docs

### ISSUE THREAD

**Issue by nperez0111** [ueberdosis/tiptap-docs#35]
The custom LLM docs could be improved, to specify how to get rich-text streaming from a custom LLM.

The gist of it is that you need the LLM to respond with HTML which allows the editor to parse this into rich-text. The reason we do not support markdown is that we don't want to ship a whole markdown parser to your frontend just for LLM responses.

**Comment by kart-c** [comment]
I can pick this up if it's alright. I would also like to update the below type in screenshot to the ones mentioned in the table.
![image](https://github.com/user-attachments/assets/af0c6e3c-a34c-4993-bacd-9acea0ac5f24)

| Type | Method name | Return Type |
|--------|--------|--------|
| completion | aiCompletionResolver | Promise<ReadableStream<Uint8Array> \| null> |
| streaming | aiStreamResolver | Promise<string \| null> |
| image | aiImageResolver | Promise<string \| null> |

**Comment by nperez0111** [comment]
Appreciate it @kart-c
