### ISSUE TITLE
Dependency Conflict with @tiptap/react and React 19

### ISSUE THREAD

**Issue by ALEXDINO7** [ueberdosis/tiptap-docs#50]
I'm encountering a dependency conflict while trying to install the @tiptap/react package alongside React version 19 after installing Next.js (version 15.0.1) using create-next-app.

Environment

- Project Name: frontend
- Node Version: v20.7.0
- NPM Version: v10.1.0
- Next.js Version: 15.0.1
- React Version: 19.0.0-rc-69d4b800-20241021
- @tiptap/react Version: 2.9.1

**Error Message**

```

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@19.0.0-rc-69d4b800-20241021
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-69d4b800-20241021" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0 || ^18.0.0" from @tiptap/react@2.9.1
npm ERR! node_modules/@tiptap/react
npm ERR!   @tiptap/react@"*" from the root project
```

**Comment by alexvcasillas** [comment]
You need to use `--legacy-peer-deps` if you want to install it within a `Next.js` app that uses React 19 :)

**Comment by ALEXDINO7** [comment]
> --legacy-peer-deps

thanks for your help

**Comment by alexvcasillas** [comment]
I'll close this issue as it seems to be resolved 👌🏻
